#!/usr/bin/env bash

[[ -e config-leader/ssl-certificate.yml ]] || { echo >&2 "The file ./config-leader/ssl-certificate.yml was not found in current working directory."; exit 1; }

echo "Running Pryv/ssl-certificate component."
docker-compose -f config-leader/ssl-certificate.yml up
